title: Divya Shanmugam
firstname: Divya
lastname: Shanmugam
url: "https://dmshanmugam.github.io"
baseurl:  ""
# url: "/"
author: "Divya Shanmugam"

markdown: kramdown
kramdown:
  input: GFM
  
twitter_username: dmshanmugam

header: assets/profile.png

sass:
    style: compressed
    sass_dir: _sass

footer: yes
footer_url: ""
footer_text: "***"

nav:
 - name: "Publications"
   link: "/publications"
 - name: "Misc"
   link: "/misc"
 - name: "Writing"
   link: "/blog"
 - name: "CV"
   link: "/assets/cv.pdf"

 